name: PR_Test

on:
  pull_request:
    branches: [ main ]

jobs:
  show_info:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Echo data
        run: |
          cd /github/workspace
          ls
