name: PR_Test

on:
  pull_request:
    branches: [ main ]

jobs:
  show_info:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Echo data
        run: 
          res=$(sshpass -p '${{ secrets.FUNNEL_PASS }}' ssh -o StrictHostKeyChecking=no ${{ secrets.FUNNEL_USER }}@${{ secrets.FUNNEL_HOST }} ls)
          echo $res
